// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, type PrismaConfig } from "prisma/config";

// `directUrl` is a real, CLI-enforced `datasource` option in Prisma 7.9.1 —
// unlike older Prisma versions, it can't live in schema.prisma's datasource
// block anymore ("Move connection URLs to prisma.config.ts") — but
// @prisma/config's shipped types haven't caught up yet, so it's typed here
// rather than left off the object literal, which `defineConfig` would
// reject as an unknown property.
type DatasourceConfig = NonNullable<PrismaConfig["datasource"]> & {
  directUrl?: string;
};

// Neon's pooled (PgBouncer) endpoint doesn't reliably support the
// session-scoped advisory lock `prisma migrate deploy` takes, so
// migrations/introspection use a direct, non-pooled connection instead.
// Falls back to DATABASE_URL when unset (e.g. local dev against a single
// non-pooled Postgres instance).
const datasource: DatasourceConfig = {
  url: process.env["DATABASE_URL"],
  directUrl: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource,
});
